#!/bin/bash


# Please copy this file to .git/hooks
echo $(pwd)
command -v swiftformat >/dev/null 2>&1 || { echo >&2 "SwiftFormat not installed. Aborting."; exit 0; }

command -v npm exec cspell >/dev/null 2>&1 || { echo >&2 "cSpell not installed. Aborting."; exit 0; }

command -v swiftlint >/dev/null 2>&1 || { echo >&2 "swiftlint not installed. Aborting."; exit 0; }

staged_files=$(git diff --cached --name-only --diff-filter=d | grep "\.swift$")

if [ -z "$staged_files" ]; then
    echo "No Swift files staged."
    exit 0
fi


for file in $staged_files; do
    swiftformat_result=$(swiftformat --lint "$file")
    if [ -n "$swiftformat_result" ]; then
        echo "SwiftFormat found style violations in $file:"
        echo "$swiftformat_result"
    fi
    
    swiftlint_result=$(swiftlint autocorrect "$file")
    if [ -n "$swiftlint_result" ]; then
        echo "Swiftlint found style violations in $file:"
        echo "$swiftlint_result"
    fi
done
echo "Spelling check start"
for file in $staged_files; do
    cspell_result=$(cspell lint -c cspell.json --words-only --no-progress "$file")
    if [ -n "$cspell_result" ]; then
        echo "$file:"
        echo "$cspell_result"
    fi
done

exit 0
